### PR TITLE
[hack] a script that can be used to smoke test the latest release

### PR DESCRIPTION
**Pull request by jmazzitelli**
We can now use this script after each release to confirm the helm charts that are about to be published actually work.

You should just be able to run `smoke-test-release-branch.sh` but there are some cmdline options you can use to customize it in case you want to test on, say, your own remote repo.

Also included is a new CI workflow to automatically run this script on release PRs (or any PR that modifies the published helm charts index file).

### CODE REVIEW

**Comment by jmazzitelli** [comment]
You can confirm the new github action works by looking at my test PR over in my fork: https://github.com/jmazzitelli/helm-charts/pull/2

Notice that because the helm chart index was changed (which happens when new helm charts are released), that triggered the new workflow which runs the new smoke test script. See the successful smoke test run here: https://github.com/jmazzitelli/helm-charts/actions/runs/5789207283/job/15689744162?pr=2#step:3:83

**Comment by jmazzitelli** [comment]
> (Helm: Chart=[kiali-server], Release=[kiali-server], Version=[1.61.0])

That's weird it is running with version 1.61.0. Are you testing that? Look at the output of the script and see what release branch it thinks it is using. Make sure when you pull this PR you merge it on top of a master branch.

**Comment by leandroberetta** [comment]
Yeah, it's true, but I synced my fork and it's doing the same thing, I'm not sure why it's picking: 

[HACK] Will smoke test remote release branch [origin/helm-charts-release-58-main]

Shouldn't be using master?.

**Comment by jmazzitelli** [comment]
> [HACK] Will smoke test remote release branch [origin/helm-charts-release-58-main]
> 
> Shouldn't be using master?.

No, I wrote the script so by default it will try to find the latest `helm-charts-release-*` branch (it will get all of them and then sort them so it will pick the one with the highest number - in our case that is helm-charts-release-88-main.

In fact, I don't even know how you are picking up `helm-charts-release-58-main` because that isn't even in the remote repo anymore! That branch has been deleted -- see https://github.com/kiali/helm-charts/branches/all

Do a `git remote prune origin` -- it should purge all of the old branches that we don't have anymore. It sounds like your local repo doesn't have the latest from kiali/helm-charts repo. What is your `origin` pointing to anyway? It sounds like it might not even be pointing to the correct repo. Do this and see what it says:

```
$ git remote -v | grep origin
origin	git@github.com:kiali/helm-charts.git (fetch)
origin	git@github.com:kiali/helm-charts.git (push)
```

**Comment by leandroberetta** [comment]
OK, that is the issue, I generally use "origin" for my fork, and "upstream" for the upstream repo. Now it works, I used your recommended parameter `-grn upstream`

**Review by leandroberetta — APPROVED** [review]
Looks good:

[HACK] =========================
[HACK] The smoke test has PASSED
[HACK] =========================

**Pull request merged**
