### PR TITLE
fix the affinity value names

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/3921

### CODE REVIEW

**Comment by jmazzitelli** [comment]
This needs a review.

**Comment by jmazzitelli** [comment]
To test this, you just have to run the server helm chart with a custom values.yaml that sets `deployment.affinity.pod` and `deployment.affinity.pod_anti` and make sure that those settings go in the correct spot in the server deployment. You don't even have to actually deploy it - you can use "helm template" and just look at the resultant Deployment yaml and check for correctness.

**Comment by jmazzitelli** [comment]
This looks good. Tests are OK.

Run `make build-helm-charts` to produce the new helm charts. Then run the tests like this:

```
helm template \
  kiali-server \
  -f values.yaml \
  -n istio-system \
  _output/charts/kiali-server-1.34.0-SNAPSHOT.tgz  > results.txt
```

1. With `values.yaml` set to:
```
deployment:
  affinity:
    node:
      someKey1: someValue1
```

the results.txt show this in Deployment:
```
      affinity:
        nodeAffinity:
          someKey1: someValue1
```

2. With `values.yaml` set to:

```
deployment:
  affinity:
    node:
      someKey1: someValue1
    pod:
      someKey2: someValue2
    pod_anti:
      someKey3: someValue3
```

the results.txt show this in Deployment:

```
      affinity:
        nodeAffinity:
          someKey1: someValue1
        podAffinity:
          someKey2: someValue2
        podAntiAffinity:
          someKey3: someValue3
```

**Comment by jmazzitelli** [comment]
this is all good - simple change and test shows it producing the correct yaml now.

**Review by jshaughn — APPROVED** [review]
LOK2ME

**Pull request merged**
