### PR TITLE
implement some best practices

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes https://github.com/kiali/kiali/issues/4485

### CODE REVIEW

**Comment by jmazzitelli** [comment]
this first commit provides the ability to add custom labels to the Ingress/Route

**Comment by jmazzitelli** [comment]
second commit sets the resource requests. We might also consider setting resource limits, but so far that is not implemented.

**Comment by jmazzitelli** [comment]
third commit sets the resource requests on the server. We might also consider setting resource limits, but so far that is not implemented.

**Comment by jmazzitelli** [comment]
fourth commit adds memory limits to the server pod. We are going to opt not to create memory limits for the operator pod right now

**Comment by jmazzitelli** [comment]
to test - set the helm value `deployment.ingress.additional_labels.foo=bar` and (if on non-OpenShift/minikube/kind) set `spec.deployment.ingress.enabled=true`. When you install, check that the Ingress has the label "foo: bar" and check the server pod's container to ensure it has `resources` defaults:
```yaml
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits;
    memory: 1Gi
```
If you test on OpenShift, check that the labels are on the Route (a Route is created on OpenShift, not an Ingress).

Then test by installing the operator via its helm chart and make sure it's pod container also has resources defaults:
```yaml
resources:
  requests:
    cpu: 10m
    memory: 64Mi
```

**Review by nrfox — APPROVED** [review]

**Pull request merged**
