### PR TITLE
explicitly define ANSIBLE_CONFIG so an admin can more easily change it

### PR DESCRIPTION
**Pull request by jmazzitelli**
this goes with https://github.com/kiali/kiali/issues/3469

### CODE REVIEW

**Comment by jmazzitelli** [comment]
To enable the profiler:
```
kubectl set env deploy/kiali-operator -n kiali-operator -e ANSIBLE_CONFIG=/opt/ansible/ansible-profiler.cfg
```
To disable it:
```
kubectl set env deploy/kiali-operator -n kiali-operator -e ANSIBLE_CONFIG=/etc/ansible/ansible.cfg
```

**Comment by jmazzitelli** [comment]
Adding @FilipB as a reviewer - he was able to use this new profiling feature so he can confirm changing this new env var works.

**Review by jshaughn — APPROVED** [review]
LOK

**Review by FilipB — COMMENTED** [review]
Tried to enable/disable. Checked operator log. Works as expected.

**Pull request merged**
