### PR TITLE
Allow kiali to consume DaemonSets

### PR DESCRIPTION
**Pull request by xeviknal**
needs https://github.com/kiali/kiali/pull/3764

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]
ltgm

**Review by aljesusg — APPROVED** [review]
LGFM

**Comment by xeviknal** [comment]
@aljesusg @lucasponce should we merge the operator one too, since this one is merged? I don't fully know what happens if you have helm-charts and operator files not fully-syncronized. At least, give a build and deploy a try in master.

**Comment by lucasponce** [comment]
On this case it's harmless, but we should avoid to merge operator/helm PRs until the backend/frontend work is ready and discussions resolved.

(This changes will simply be not used until the backend changes in workloads are consolidated).

**Pull request merged**
