### PR TITLE
conform to the correct route syntax for target port

### PR DESCRIPTION
**Pull request by jmazzitelli**
part of: https://github.com/kiali/kiali/issues/4255

### CODE REVIEW

**Comment by israel-hdez** [comment]
no backport to v1.36 for this one?

**Comment by jmazzitelli** [comment]
> no backport to v1.36 for this one?

no, because we don't use the helm charts for our production v1.36 builds, so no need for this to be backported.

**Comment by jmazzitelli** [comment]
> no backport to v1.36 for this one?

since its trivial, I'll just create a backport PR just to be consistent with everything else we are doing

**Review by israel-hdez — APPROVED** [review]
LGTM

**Pull request merged**
