### PR TITLE
support mounting custom secrets in the kiali pod

### PR DESCRIPTION
**Pull request by jmazzitelli**
part of: https://github.com/kiali/kiali/issues/4468

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Here's how you can test assuming you have istio installed in istio-system namespace:

```
helm install -n istio-system kiali-server _output/charts/kiali-server-*-SNAPSHOT.tgz \
   --set deployment.custom_secrets[0].name=mazz \
   --set deployment.custom_secrets[0].mount=/mazzpath \
   --set deployment.custom_secrets[0].optional=true \
   --set deployment.custom_secrets[1].name=foo \
   --set deployment.custom_secrets[1].mount=/foopath \
   --set deployment.custom_secrets[1].optional=true
```

Now see that the Kiali pod has the correct yaml (I did not create the secrets, but with optional=true it doesn't matter that the secrets actually exist - just knowing the pod started successfully and has the correct yaml is good):

See the volumeMounts exist:

```
$ for s in mazz foo; do kubectl get pods -n istio-system -l app=kiali -o jsonpath="{.items[0].spec.containers[0].volumeMounts[?(@.name==\"${s}\")]}" | jq; done
{
  "mountPath": "/mazzpath",
  "name": "mazz"
}
{
  "mountPath": "/foopath",
  "name": "foo"
}
```

See the volumes exist:

```
$ for s in mazz foo; do kubectl get pods -n istio-system -l app=kiali -o jsonpath="{.items[0].spec.volumes[?(@.name==\"${s}\")]}" | jq; done
{
  "name": "mazz",
  "secret": {
    "defaultMode": 420,
    "optional": true,
    "secretName": "mazz"
  }
}
{
  "name": "foo",
  "secret": {
    "defaultMode": 420,
    "optional": true,
    "secretName": "foo"
  }
}
```

**Comment by jmazzitelli** [comment]
testing looks good: https://github.com/kiali/kiali/issues/4468#issuecomment-963748833

**Review by jshaughn — APPROVED** [review]
LOK

**Comment by jmazzitelli** [comment]
assigning to @mattmahoneyrh so he can determine if the community testing and molecule testing is good enough.

**Pull request merged**
